### ISSUE TITLE
feat: QFeatures needs to implement an `updateObject()` method

### ISSUE THREAD

**Issue by cvanderaa** [lgatto/Features#152]
From a conversation with Hervé Pagès on Slack about whether to implement an `updateObject()` or not:

>No simple answer to that. It depends.

>1. First of all if the new class is for objects that are not meant to be serialized then updateObject() is not needed. For example nobody should ever serialize a TxDb object.
>2. Another situation where maybe there's no need to define a specific updateObject() method for a new class B is if the new class extends a class A that already has an updateObject() method, and adds slots that are meant to contain only ordinary vectors or other base R objects. Then calling updateObject() on objects of class B will do the right thing i.e. it will update the parts of the object that are under the control of A and will ignore the new slots. All this is fine until the author of class B decides to make changes to the class definition e.g. to add more slots. When this happens, they'll need to implement an updateObject() method for their objects (this method will need to call callNextMethod() and that call should happen at the very end of the method body).
>3. If, OTOH, B extends A by adding slots that are meant to contain other S4 objects, then it's recommended to define an updateObject() method for B. This method would simply update the new slots containing S4 objects by calling updateObject() on each of them, and call callNextMethod() at the end.
>4. If the new class does not extend anything then calling updateObject() on these objects will call the updateObject,ANY method defined in BiocGenerics. This default updateObject() method will probably do the right thing, until the author of the new class makes a change to the internal of their class. When this happens, they'll need to implement a specific updateObject() method for their class of course.

>In any case calling updateObject() on an S4 object is expected to work, even if it doesn't do anything (no-op). So I'd say that authors of a new class should make sure that updateObject() doesn't return an error on their objects.

I would say `QFeatures` belongs to 3. since its need to update the `@assayLinks` slot that expects an S4 object of class `AssayLinks`. Therefore we need to implement an `updateObject()` method to update the `@assayLinks`.

**Comment by lgatto** [comment]
Indeed. Thank you for all this information!

**Comment by cvanderaa** [comment]
Shall I work on it?

**Comment by lgatto** [comment]
Yes, please. Thanks

**Comment by cvanderaa** [comment]
Solved by #153
