### ISSUE TITLE
Agregation failed with adjMat containing empty columns (proteins)

### ISSUE THREAD

**Issue by samWieczorek** [lgatto/Features#159]
This type of adjacency matrix may occur if there are proteins that contain only shared peptides and one want to aggregate on ly on specific peptides. Thus, the adjacency matrix will have some empty rows and columns.

Here is a minimal reproducible example

```r
>data("feat1")
>feat1 <- aggregateFeatures(feat1, "psms", "Sequence", name = "peptides")
>rowData(feat1[["peptides"]])$Protein[3] <- c("ProtA;ProtB;ProtC")
>X <- makeAdjacencyMatrix(rowData(feat1[[2]])[,'Protein'])
>X[3,] <- 0 # Only specific peptides
>rownames(X) <- rownames(feat1[[2]])
>adjacencyMatrix(feat1[[2]]) <- X

>object <- aggregateFeatures(object = feat1, 
                          i = 2, 
                          name = 'proteins',
                          fcol = "adjacencyMatrix", 
                          fun = colMeansMat)
```

**Comment by lgatto** [comment]
Your adjacency matrix is

```r
3 x 3 sparse Matrix of class "dgCMatrix"
            ProtA ProtB ProtC
ELGNDAYK        1     .     .
IAEESNFPFIK     .     1     .
SYGFNAAR        .     .     .
```
which indicates that you have a peptide, SYGFNAAR, that doesn't belong to any protein and a protein, ProtC, that isn't identified by any peptide. How would these be possible?

**Comment by lgatto** [comment]
I have added an [adjacency matrix validity function](https://github.com/rformassspectrometry/QFeatures/commit/f72ab0c408ca239dc66133c7df28d89b8da2ad2b) that check that such situation don't happen:

```r
> adjacencyMatrix(feat1[[2]]) <- X
Error in validAdjacencyMatrix(value) : 
  rowSums() == 0 detected: peptides must belong to at least one proteins.
```

**Comment by lgatto** [comment]
Closing but feel free to re-open and discuss further.
