### ISSUE TITLE
using filterFeatures on selected assays

### ISSUE THREAD

**Issue by lmsimp** [lgatto/Features#179]
Hi Laurent and Chris, 

I would like to use `filterFeatures` on only one or a subset of selected assays in a QF object. If I understand the function and documentation correctly this is not possible and `filterFeatures` currently by default goes through each assay of the QF object and filters **all** assays?

To achieve filtering on only, say one specific assay, I guess my only option (if I want to make use of `filterFeatures` function and not do this in manually) is to make a copy of the QF, run `filterFeatures`, extract my assay, then add back to the original using `addAssay`?

Would you consider setting a way to allow users to select the assay(s) to run the filtering on?

Thanks, Lisa

CCing @Charl-Hutchings

**Comment by lgatto** [comment]
This feature is on its way.
