### ISSUE TITLE
Rethink assays nomenclature 

### ISSUE THREAD

**Issue by cvanderaa** [lgatto/Features#194]
As discussed for the protocol paper with @samgregoire, the fact that the quantitative data in a `SummarizedExperiment` and the data objects in a `QFeatures` are both called `assays` complicates the description of the data structure. 

I would suggest renaming the `QFeatures`' `assays`. 
-  `sets`: it is generic, like data sets (and in honor of the previously supported `ExpressionSet` class)
- `experiments`: because each object is a `[SingleCell|Summarized]Experiment`. Actually, the objects in `QFeatures` are retrieved using `experiments(qf)`.
- `elements`: because each object is in fact an element of a list (`ExperimentList`)
- other?

**Comment by lmsimp** [comment]
Following @cvanderaa 😀 as you know we use `QFeatures` extensively in our lab and we have thought the same 👍 

CCing @charl-hutchings @csdaw

**Comment by lgatto** [comment]
Could you share your thoughts on this. In our latest paper, we refer to the elements of a QFeatures object as sets. (@samgregoire, could you confirm).

**Comment by samgregoire** [comment]
I confirm. 
- We use `assay` or quantitative `assay` to refer to `SummarizedExperiment`'s quantitative data (since they are extracted using the `assay()` function).
- We use `sets` to refer to data objects in a `QFeatures`.

**Comment by lmsimp** [comment]
This great 👍 I think `sets` works well but any of Chris' suggestions above would be preferable over `assays`.

**Comment by tavareshugo** [comment]
my vote for "experiments" based on discussions on #197
